--------------------------------------------------------------------------
--script for auto_funcs.h and auto_funcs.cpp generation
--expects LuaJIT
--------------------------------------------------------------------------
--load parser module
package.path = package.path..";../../cimgui/generator/?.lua"
local cpp2ffi = require"cpp2ffi"
local copyfile = cpp2ffi.copyfile
--take script args---------------------------
local COMPILER, CPRE = cpp2ffi.GetScriptArgs({},...)
--str_subst
local pat = [[ \t{%[%(]]
local str_subst = {
	[pat] = [[ \t\x7B[(]]
}
--------------------------------------------------------------------------
--this table has the functions to be skipped in generation
--------------------------------------------------------------------------

local cimgui_manuals = {
    Palette_Palette = true,
	Palette_destroy = true,
	Palette_set = true,
}
local cimgui_skipped = {
	--TextEditor_GetText = true,
	--TextEditor_SetTextLines = true,
	--TextEditor_GetTextLines = true,
}
--------------------------------------------------------------------------
--this table is a dictionary to force a naming of function overloading (instead of algorythmic generated)
--first level is cimguiname without postfix, second level is the signature of the function, value is the
--desired name
---------------------------------------------------------------------------
local cimgui_overloads = {
    --igPushID = {
        --["(const char*)"] =           "igPushIDStr",
        --["(const char*,const char*)"] = "igPushIDRange",
        --["(const void*)"] =           "igPushIDPtr",
        --["(int)"] =                   "igPushIDInt"
    --},
}

--------------------------header definitions
local cimgui_header = 
[[//This file is automatically generated by generator.lua from https://github.com/goossens/ImGuiColorTextEdit
//based on TextEditor.h file version XXX from https://github.com/goossens/ImGuiColorTextEdit
]]
--------------------------------------------------------------------------
--helper functions
--------------------------------

--------------------------------------------------------
-----------------------------do it----------------------
--------------------------------------------------------


-------------funtion for parsing implot headers
local function parseImGuiHeader(header, names, modulename)
	--prepare parser
	local parser = cpp2ffi.Parser()
	parser.modulename = modulename
	parser.getCname = function(stname,funcname,namespace)
		local pre = (stname == "") and (namespace and (namespace=="ImGui" and "ig" or namespace.."_") or "") or stname.."_"
		return pre..funcname
	end
	parser.cname_overloads = cimgui_overloads

	parser:set_manuals(cimgui_manuals, modulename)
	parser.skipped = cimgui_skipped
	parser.str_subst = str_subst
	parser.cimgui_inherited =  dofile([[../../cimgui/generator/output/structs_and_enums.lua]])
	
	local include_cmd = COMPILER=="cl" and [[ /I ]] or [[ -I ]]
	local extra_includes = include_cmd.." ../../cimgui "
	..include_cmd.." ../../cimgui/imgui "
	
	parser:take_lines(CPRE..extra_includes..header, names, COMPILER)
	
	return parser
end
--generation
print("------------------generation with "..COMPILER.."------------------------")
local modulename = "cimCTE"
local headerst = [[
#include "../ImGuiColorTextEdit/TextDiff.h"
#include "../ImGuiColorTextEdit/extras/TrieAutoComplete.h"
#include "../ImGuiColorTextEdit/extras/Notifications.h"
]]

cpp2ffi.save_data("headers.h",headerst)
local parser1 = parseImGuiHeader("headers.h", {[[TextEditor]],[[TextDiff]],[[TrieAutoComplete]],[[Notifications]]}, modulename)
os.remove"headers.h"
parser1:do_parse()
parser1:cimgui_generation(cimgui_header)
parser1:save_output()

print"all done!!"
