//This file is automatically generated by generator.lua from https://github.com/cimgui/imnodes
//based on imnodes.h file version XXX from https://github.com/Nelarius/imnodes
#ifndef CIMGUICTE_INCLUDED
#define CIMGUICTE_INCLUDED

#include "cimgui.h"

#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS

typedef struct TextEditor TextEditor;
struct CursorPosition
{ int line; int column;
};
typedef struct CursorPosition CursorPosition;

struct CursorSelection
{ CursorPosition start; CursorPosition end;
};
typedef struct CursorSelection CursorSelection;

typedef enum {
  alignTop,
  alignMiddle,
  alignBottom
 }Scroll;
struct Decorator
{
  int line;
  float width;
  float height;
  ImVec2_c glyphSize;
  void* userData;
};
typedef struct Decorator Decorator;

typedef enum {
text=0,
keyword=1,
declaration=2,
number=3,
string=4,
punctuation=5,
preprocessor=6,
identifier=7,
knownIdentifier=8,
comment=9,
background=10,
cursor=11,
selection=12,
whitespace=13,
matchingBracketBackground=14,
matchingBracketActive=15,
matchingBracketLevel1=16,
matchingBracketLevel2=17,
matchingBracketLevel3=18,
matchingBracketError=19,
lineNumber=20,
currentLineNumber=21,
count=22,
}Color;
struct Glyph
{
  ImWchar codepoint;
  Color color;
};
typedef struct Glyph Glyph;

struct Trie
{
};
typedef struct Trie Trie;

struct CodePoint
{
};
typedef struct CodePoint CodePoint;

struct TextEditor
{
};
typedef struct CursorPosition CursorPosition;
typedef struct CursorSelection CursorSelection;
typedef struct Change* Change_opq;

typedef struct Decorator Decorator;
typedef struct Palette* Palette_opq;

typedef struct Glyph Glyph;
typedef struct Iterator* Iterator_opq;

typedef struct Language* Language_opq;

typedef struct AutoCompleteState* AutoCompleteState_opq;

typedef struct AutoCompleteConfig* AutoCompleteConfig_opq;

typedef struct Trie Trie;
typedef struct CodePoint CodePoint;
#else
#endif // CIMGUI_DEFINE_ENUMS_AND_STRUCTS





#ifndef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
typedef TextEditor::CodePoint CodePoint;
typedef TextEditor::CursorPosition CursorPosition;
typedef TextEditor::CursorSelection CursorSelection;
typedef TextEditor::Decorator Decorator;
typedef TextEditor::Glyph Glyph;
typedef TextEditor::Trie Trie;
typedef TextEditor::Color Color;
typedef TextEditor::Scroll Scroll;
typedef std::vector<std::string> std_vector_std_string;
typedef const TextEditor::AutoCompleteConfig* AutoCompleteConfig_opq;
typedef const TextEditor::AutoCompleteState* AutoCompleteState_opq;
typedef const TextEditor::Change* Change_opq;
typedef const TextEditor::Iterator* Iterator_opq;
typedef const TextEditor::Language* Language_opq;
typedef const TextEditor::Palette* Palette_opq;
#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS
CIMGUI_API TextEditor* TextEditor_TextEditor(void);
CIMGUI_API void TextEditor_destroy(TextEditor* self);
CIMGUI_API void TextEditor_SetTabSize(TextEditor* self,int value);
CIMGUI_API int TextEditor_GetTabSize(TextEditor* self);
CIMGUI_API void TextEditor_SetInsertSpacesOnTabs(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsInsertSpacesOnTabs(TextEditor* self);
CIMGUI_API void TextEditor_SetLineSpacing(TextEditor* self,float value);
CIMGUI_API float TextEditor_GetLineSpacing(TextEditor* self);
CIMGUI_API void TextEditor_SetReadOnlyEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsReadOnlyEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetAutoIndentEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsAutoIndentEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetShowWhitespacesEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsShowWhitespacesEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetShowSpacesEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsShowSpacesEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetShowTabsEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsShowTabsEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetShowLineNumbersEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsShowLineNumbersEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetShowScrollbarMiniMapEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsShowScrollbarMiniMapEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetShowPanScrollIndicatorEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsShowPanScrollIndicatorEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetShowMatchingBrackets(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsShowingMatchingBrackets(TextEditor* self);
CIMGUI_API void TextEditor_SetCompletePairedGlyphs(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsCompletingPairedGlyphs(TextEditor* self);
CIMGUI_API void TextEditor_SetOverwriteEnabled(TextEditor* self,bool value);
CIMGUI_API bool TextEditor_IsOverwriteEnabled(TextEditor* self);
CIMGUI_API void TextEditor_SetMiddleMousePanMode(TextEditor* self);
CIMGUI_API void TextEditor_SetMiddleMouseScrollMode(TextEditor* self);
CIMGUI_API bool TextEditor_IsMiddleMousePanMode(TextEditor* self);
CIMGUI_API void TextEditor_SetText(TextEditor* self,const char* text);
CIMGUI_API const char* TextEditor_GetText(TextEditor* self);
CIMGUI_API const char* TextEditor_GetCursorText(TextEditor* self,size_t cursor);
CIMGUI_API const char* TextEditor_GetLineText(TextEditor* self,int line);
CIMGUI_API const char* TextEditor_GetSectionText(TextEditor* self,int startLine,int startColumn,int endLine,int endColumn);
CIMGUI_API void TextEditor_ReplaceSectionText(TextEditor* self,int startLine,int startColumn,int endLine,int endColumn,const char* text);
CIMGUI_API void TextEditor_ClearText(TextEditor* self);
CIMGUI_API bool TextEditor_IsEmpty(TextEditor* self);
CIMGUI_API int TextEditor_GetLineCount(TextEditor* self);
CIMGUI_API void TextEditor_Render(TextEditor* self,const char* title,const ImVec2_c size,bool border);
CIMGUI_API void TextEditor_SetFocus(TextEditor* self);
CIMGUI_API void TextEditor_Cut(TextEditor* self);
CIMGUI_API void TextEditor_Copy(TextEditor* self);
CIMGUI_API void TextEditor_Paste(TextEditor* self);
CIMGUI_API void TextEditor_Undo(TextEditor* self);
CIMGUI_API void TextEditor_Redo(TextEditor* self);
CIMGUI_API bool TextEditor_CanUndo(TextEditor* self);
CIMGUI_API bool TextEditor_CanRedo(TextEditor* self);
CIMGUI_API size_t TextEditor_GetUndoIndex(TextEditor* self);
CIMGUI_API void TextEditor_SetCursor(TextEditor* self,int line,int column);
CIMGUI_API void TextEditor_SelectAll(TextEditor* self);
CIMGUI_API void TextEditor_SelectLine(TextEditor* self,int line);
CIMGUI_API void TextEditor_SelectLines(TextEditor* self,int start,int end);
CIMGUI_API void TextEditor_SelectRegion(TextEditor* self,int startLine,int startColumn,int endLine,int endColumn);
CIMGUI_API void TextEditor_SelectToBrackets(TextEditor* self,bool includeBrackets);
CIMGUI_API void TextEditor_GrowSelectionsToCurlyBrackets(TextEditor* self);
CIMGUI_API void TextEditor_ShrinkSelectionsToCurlyBrackets(TextEditor* self);
CIMGUI_API void TextEditor_AddNextOccurrence(TextEditor* self);
CIMGUI_API void TextEditor_SelectAllOccurrences(TextEditor* self);
CIMGUI_API bool TextEditor_AnyCursorHasSelection(TextEditor* self);
CIMGUI_API bool TextEditor_AllCursorsHaveSelection(TextEditor* self);
CIMGUI_API bool TextEditor_CurrentCursorHasSelection(TextEditor* self);
CIMGUI_API void TextEditor_ClearCursors(TextEditor* self);
CIMGUI_API size_t TextEditor_GetNumberOfCursors(TextEditor* self);
CIMGUI_API void TextEditor_GetCursor_size_t(TextEditor* self,int* line,int* column,size_t cursor);
CIMGUI_API void TextEditor_GetCursor_IntPtr(TextEditor* self,int* startLine,int* startColumn,int* endLine,int* endColumn,size_t cursor);
CIMGUI_API void TextEditor_GetMainCursor(TextEditor* self,int* line,int* column);
CIMGUI_API void TextEditor_GetCurrentCursor(TextEditor* self,int* line,int* column);
CIMGUI_API CursorPosition TextEditor_GetMainCursorPosition(TextEditor* self);
CIMGUI_API CursorPosition TextEditor_GetCurrentCursorPosition(TextEditor* self);
CIMGUI_API CursorPosition TextEditor_GetCursorPosition(TextEditor* self,size_t cursor);
CIMGUI_API CursorSelection TextEditor_GetCursorSelection(TextEditor* self,size_t cursor);
CIMGUI_API CursorSelection TextEditor_GetMainCursorSelection(TextEditor* self);
CIMGUI_API const char* TextEditor_GetWordAtScreenPos(TextEditor* self,const ImVec2_c screenPos);
CIMGUI_API void TextEditor_ScrollToLine(TextEditor* self,int line,Scroll alignment);
CIMGUI_API int TextEditor_GetFirstVisibleLine(TextEditor* self);
CIMGUI_API int TextEditor_GetLastVisibleLine(TextEditor* self);
CIMGUI_API int TextEditor_GetFirstVisibleColumn(TextEditor* self);
CIMGUI_API int TextEditor_GetLastVisibleColumn(TextEditor* self);
CIMGUI_API float TextEditor_GetLineHeight(TextEditor* self);
CIMGUI_API float TextEditor_GetGlyphWidth(TextEditor* self);
CIMGUI_API void TextEditor_SelectFirstOccurrenceOf(TextEditor* self,const char* text,bool caseSensitive,bool wholeWord);
CIMGUI_API void TextEditor_SelectNextOccurrenceOf(TextEditor* self,const char* text,bool caseSensitive,bool wholeWord);
CIMGUI_API void TextEditor_SelectAllOccurrencesOf(TextEditor* self,const char* text,bool caseSensitive,bool wholeWord);
CIMGUI_API void TextEditor_ReplaceTextInCurrentCursor(TextEditor* self,const char* text);
CIMGUI_API void TextEditor_ReplaceTextInAllCursors(TextEditor* self,const char* text);
CIMGUI_API void TextEditor_OpenFindReplaceWindow(TextEditor* self);
CIMGUI_API void TextEditor_CloseFindReplaceWindow(TextEditor* self);
CIMGUI_API void TextEditor_SetFindButtonLabel(TextEditor* self,const char* label);
CIMGUI_API void TextEditor_SetFindAllButtonLabel(TextEditor* self,const char* label);
CIMGUI_API void TextEditor_SetReplaceButtonLabel(TextEditor* self,const char* label);
CIMGUI_API void TextEditor_SetReplaceAllButtonLabel(TextEditor* self,const char* label);
CIMGUI_API bool TextEditor_HasFindString(TextEditor* self);
CIMGUI_API void TextEditor_FindNext(TextEditor* self);
CIMGUI_API void TextEditor_FindAll(TextEditor* self);
CIMGUI_API void TextEditor_AddMarker(TextEditor* self,int line,ImU32 lineNumberColor,ImU32 textColor,const char* lineNumberTooltip,const char* textTooltip);
CIMGUI_API void TextEditor_ClearMarkers(TextEditor* self);
CIMGUI_API bool TextEditor_HasMarkers(TextEditor* self);
CIMGUI_API void TextEditor_SetUserData(TextEditor* self,int line,void* data);
CIMGUI_API void* TextEditor_GetUserData(TextEditor* self,int line);
CIMGUI_API void TextEditor_ClearLineDecorator(TextEditor* self);
CIMGUI_API bool TextEditor_HasLineDecorator(TextEditor* self);
CIMGUI_API void TextEditor_ClearLineNumberContextMenuCallback(TextEditor* self);
CIMGUI_API bool TextEditor_HasLineNumberContextMenuCallback(TextEditor* self);
CIMGUI_API void TextEditor_ClearTextContextMenuCallback(TextEditor* self);
CIMGUI_API bool TextEditor_HasTextContextMenuCallback(TextEditor* self);
CIMGUI_API void TextEditor_IndentLines(TextEditor* self);
CIMGUI_API void TextEditor_DeindentLines(TextEditor* self);
CIMGUI_API void TextEditor_MoveUpLines(TextEditor* self);
CIMGUI_API void TextEditor_MoveDownLines(TextEditor* self);
CIMGUI_API void TextEditor_ToggleComments(TextEditor* self);
CIMGUI_API void TextEditor_SelectionToLowerCase(TextEditor* self);
CIMGUI_API void TextEditor_SelectionToUpperCase(TextEditor* self);
CIMGUI_API void TextEditor_StripTrailingWhitespaces(TextEditor* self);
CIMGUI_API void TextEditor_TabsToSpaces(TextEditor* self);
CIMGUI_API void TextEditor_SpacesToTabs(TextEditor* self);
CIMGUI_API void TextEditor_SetPalette(TextEditor* self,const Palette_opq newPalette);
CIMGUI_API const Palette_opq TextEditor_GetPalette(TextEditor* self);
CIMGUI_API void TextEditor_SetDefaultPalette(const Palette_opq aValue);
CIMGUI_API Palette_opq TextEditor_GetDefaultPalette(void);
CIMGUI_API const Palette_opq TextEditor_GetDarkPalette(void);
CIMGUI_API const Palette_opq TextEditor_GetLightPalette(void);
CIMGUI_API Glyph* Glyph_Glyph_Nil(void);
CIMGUI_API void Glyph_destroy(Glyph* self);
CIMGUI_API Glyph* Glyph_Glyph_Wchar(ImWchar cp);
CIMGUI_API Glyph* Glyph_Glyph_WcharColor(ImWchar cp,Color col);
CIMGUI_API const Language_opq Language_C(void);
CIMGUI_API const Language_opq Language_Cpp(void);
CIMGUI_API const Language_opq Language_Cs(void);
CIMGUI_API const Language_opq Language_AngelScript(void);
CIMGUI_API const Language_opq Language_Lua(void);
CIMGUI_API const Language_opq Language_Python(void);
CIMGUI_API const Language_opq Language_Glsl(void);
CIMGUI_API const Language_opq Language_Hlsl(void);
CIMGUI_API const Language_opq Language_Json(void);
CIMGUI_API const Language_opq Language_Markdown(void);
CIMGUI_API const Language_opq Language_Sql(void);
CIMGUI_API void TextEditor_SetLanguage(TextEditor* self,const Language_opq l);
CIMGUI_API const Language_opq TextEditor_GetLanguage(TextEditor* self);
CIMGUI_API bool TextEditor_HasLanguage(TextEditor* self);
CIMGUI_API const char* TextEditor_GetLanguageName(TextEditor* self);
CIMGUI_API void TextEditor_SetAutoCompleteConfig(TextEditor* self,const AutoCompleteConfig_opq config);
CIMGUI_API Trie* Trie_Trie(void);
CIMGUI_API void Trie_destroy(Trie* self);
CIMGUI_API void Trie_clear(Trie* self);
CIMGUI_API void Trie_insert(Trie* self,const char* word);
CIMGUI_API size_t CodePoint_write(char* i,ImWchar codepoint);
CIMGUI_API bool CodePoint_isLetter(ImWchar codepoint);
CIMGUI_API bool CodePoint_isNumber(ImWchar codepoint);
CIMGUI_API bool CodePoint_isWord(ImWchar codepoint);
CIMGUI_API bool CodePoint_isWhiteSpace(ImWchar codepoint);
CIMGUI_API bool CodePoint_isXidStart(ImWchar codepoint);
CIMGUI_API bool CodePoint_isXidContinue(ImWchar codepoint);
CIMGUI_API bool CodePoint_isLower(ImWchar codepoint);
CIMGUI_API bool CodePoint_isUpper(ImWchar codepoint);
CIMGUI_API ImWchar CodePoint_toUpper(ImWchar codepoint);
CIMGUI_API ImWchar CodePoint_toLower(ImWchar codepoint);
CIMGUI_API bool CodePoint_isPairOpener(ImWchar ch);
CIMGUI_API bool CodePoint_isPairCloser(ImWchar ch);
CIMGUI_API ImWchar CodePoint_toPairCloser(ImWchar ch);
CIMGUI_API ImWchar CodePoint_toPairOpener(ImWchar ch);
CIMGUI_API bool CodePoint_isMatchingPair(ImWchar open,ImWchar close);
CIMGUI_API bool CodePoint_isBracketOpener(ImWchar ch);
CIMGUI_API bool CodePoint_isBracketCloser(ImWchar ch);
CIMGUI_API bool CodePoint_isMatchingBrackets(ImWchar open,ImWchar close);


///////////////manual generated
//allocates new memory that must be freed with TextEditor_GetText_free
CIMGUI_API char* TextEditor_GetText_alloc(TextEditor* self);
CIMGUI_API void TextEditor_GetText_free(char* ptr);
//returned value must be used to copy value before calling TextEditor_GetText_static again
CIMGUI_API const char* TextEditor_GetText_static(TextEditor* self);
CIMGUI_API void TextEditor_IterateIdentifiers(TextEditor* self, void(*cb)(const char *));
#endif //CIMGUICTE_INCLUDED




